Hometask_12
nikolaygurev/MADE_algorithms_and_data_structures pull request #18
Opened 2019-12-12 08:03 UTC by nikolaygurev

2019-12-22 11:21 UTC, smatskevich requested changes
Исправьте, пожалуйста.

2019-12-22 11:21 UTC, smatskevich commented on Hometask_12/main.cpp
> +            BridgeDFS(v, visited, parent, disc_time, low_time, bridges, time);
Рекурсия запрещена.

2019-12-25 00:53 UTC, smatskevich requested changes
Не пройдены тесты по TL.
TL на тесте с 4000 вершинами.
Попробуйте оптимизировать.

2020-02-18 20:21 UTC, nikolaygurev commented on Hometask_12/main.cpp
> +            BridgeDFS(v, visited, parent, disc_time, low_time, bridges, time);
Реализовал итеративный алгоритм, но он не проходит по времени

2020-02-18 20:23 UTC, nikolaygurev commented
> Не пройдены тесты по TL.
> TL на тесте с 4000 вершинами.
> Попробуйте оптимизировать.

2020-02-18 22:58 UTC, nikolaygurev commented
> Исправьте, пожалуйста.

Реализовал итеративный алгоритм

2020-02-18 22:59 UTC, nikolaygurev commented
> Не пройдены тесты по TL.
> TL на тесте с 4000 вершинами.
> Попробуйте оптимизировать.

Так и не получилось ускорить итеративный алгоритм

2020-02-18 23:00 UTC, merged